#server.servlet.context-path=/monolito365
#server.port=8080
server:
  port: 8080
  servlet:
    contextPath: /monolito365

#logging.level.root=INFO
#logging.pattern.console=%5p : %40c{1} - %m%n
logging:
  level:
    root: INFO
  pattern:
    console: "${spring.application.name} > %-5p : %40.40c{1}[%20.20M:%4L] - %m%n"
    
#org.hibernate.sql=true
org:
  hibernate:
    sql: true

#application.folder.proyectos=./proyectos
application:
  folder:
    proyectos: ./proyectos
    
#spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ssZ
#spring.jackson.time-zone=America/Bogota
#spring.jackson.time-zone=America/Mexico_City
#spring.batch.initialize-schema=never
#spring.cache.type=none
#spring.jpa.open-in-view=false
#spring.jpa.generate-ddl=false
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
#spring.jpa.properties.hibernate.show_sql=true
#spring.jpa.properties.hibernate.format_sql=false
#spring.jpa.properties.hibernate.use_sql_comments=true
#spring.jpa.properties.hibernate.type=trace
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL82Dialect
#spring.datasource.platform=postgresql
#spring.datasource.url=jdbc:postgresql://192.168.1.20:5432/postgres
#spring.datasource.username=postgres
#spring.datasource.password=rootroot
#spring.datasource.driver-class-name=org.postgresql.Driver
spring:
  application:
    name: monolito365
  jackson:
    dateFormat: yyyy-MM-dd'T'HH:mm:ssZ
    timeZone: America/Bogota
    #timeZone: America/Mexico_City
  batch:
    initializeSchema: never
  cache:
    type: none
  output:
    ansi:
      enabled: DETECT
  jpa:
    openInView: false
    generateDdl: false
    hibernate:
      ddlAuto: none
      naming:
        physicalStrategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicitStrategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        showSql: true
        formatSql: false
        useSqlComments: true
        type: trace
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
  datasource:
    platform: postgresql
    url: jdbc:postgresql://localhost:5432/postgres
    #url: jdbc:postgresql://192.168.1.8:5432/postgres
    #jndi-name: java:jboss/datasources/postgresqlDS
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    
##security.oauth2.resource.filter-order=3
  security:
    oauth:
    resource:
    filter-order: 3

